apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: portainer-transport
  namespace: external-routes
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-portainer-http
  namespace: external-routes
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`manage.steppler.cloud`)
      kind: Rule
      services:
        - name: external-portainer-https-svc
          port: 443
          scheme: https
          serversTransport: portainer-transport
  tls:
    secretName: "letsencrypt-wildcard-cert-prod"
