apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: external-portainer-tcp
  namespace: external-routes
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`manage.steppler.cloud`)
      services:
        - name: external-portainer-tcp-svc
          port: 443
  tls:
    passthrough: true
