apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-portainer-https
  namespace: external-routes
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`manage.steppler.cloud`)
      kind: Rule
      services:
        - name: external-portainer-https-svc
          port: 9443
  tls:
    secretName: "letsencrypt-wildcard-cert-prod"
