apiVersion: v1
kind: Service
metadata:
  name: external-portainer-http-svc
  namespace: external-routes
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-portainer-http-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.198.114
    ports:
      - name: http
        port: 9443
        protocol: TCP
