apiVersion: v1
kind: Service
metadata:
  name: external-portainer-https-svc
  namespace: external-routes
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-portainer-https-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.198.114
    ports:
      - name: https
        port: 9443
