apiVersion: v1
kind: Service
metadata:
  name: external-immich-http-svc
  namespace: external-routes
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-immich-http-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.110.99
    ports:
      - name: http
        port: 2283
