apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 15m
  path: deployment/apps/jenkins
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
