apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pangolin-newt
  namespace: flux-system
spec:
  interval: 15m
  path: deployment/apps/pangolin-newt
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
