apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-komodo-http
  namespace: external-routes
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`manage.steppler.cloud`)
      kind: Rule
      services:
        - name: external-komodo-http-svc
          port: 80
      middlewares:
        - name: external-komodo-http-headers
  tls:
    secretName: "letsencrypt-wildcard-cert-prod"
