apiVersion: v1
kind: Service
metadata:
  name: external-wygiwyh-http-svc
  namespace: external-routes
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9005
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-wygiwyh-http-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.198.114
    ports:
      - name: http
        port: 9005
        protocol: TCP
